### ISSUE TITLE
RMS internal thread

### ISSUE THREAD

**Issue by brevid** [joe311/optical_threads_for_CAD#1]
I think it should be <MinorDia>0.7644</MinorDia>

**Comment by joe311** [comment]
Thanks for noticing the issue! Fixed with commit 1f8e093a857a4551e605e0d8b45649e5830e7ec9
The value is slightly different than 0.7644, here I'm following Thorlabs specs (which might be from ASA AMO standard, and the 0.7644 might be from ISO standards)
